name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Verify Formatting
      run: dotnet format GitLabMcp.sln --verify-no-changes
    - name: Restore dependencies
      run: dotnet restore GitLabMcp.sln
    - name: Build
      run: dotnet build GitLabMcp.sln --no-restore
    - name: Test
      run: dotnet test GitLabMcp.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: AlissonStochero/gitlab_mcp
